#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Show all ignored files
##? 1.0.0
##?
##? Usage:
##?   show_ignore
##?

docs::parse "$@"

# git status --ignored -s | grep "\!\!" | awk '{print $2}'
git ls-files --others --ignored --exclude-standard