#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Show the size of the current directory
#?? 1.0.0
##?
##? Usage:
##?   size_of_dir
docs::parse "$@"

# ncdu -rr -x --color dark -o- "$PWD" | less -R
ncdu -rr -x --color dark "$PWD"